### YamlMime:Lifecycle
metadata:
  title: Upravitelj konfiguracije Microsoft System Center 2012 R2
  description: Upravitelj konfiguracije Microsoft System Center 2012 R2 slijedi pravilnik o fiksnom životnom ciklusu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 61515e636a9af310a2107c9505067fa551d26b15
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "850226"
name: Upravitelj konfiguracije Microsoft System Center 2012 R2
summary: >+
  Upravitelj konfiguracije Microsoft System Center 2012 R2 slijedi pravilnik [o fiksnom](/lifecycle/policies/fixed) životnom ciklusu.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Linkovi \n* [Pravila servisnog paketa](/lifecycle/policies/fixed#service-packs)\n* [Dokumentacija za upravitelj konfiguracije](/mem/configmgr/core/misc/online-documentation)"
