### YamlMime:Lifecycle
metadata:
  title: Microsoftova aplikacija za virtualizaciju Hosting 5.0 za radne ploče sustava Windows
  description: Microsoftova aplikacija Virtualization Hosting 5.0 za radne površine sustava Windows slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 47a19d53aa66987491ba097905f0388269c66ff0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4146367"
name: Microsoftova aplikacija za virtualizaciju Hosting 5.0 za radne ploče sustava Windows
summary: >+
  Microsoftova aplikacija Virtualization Hosting 5.0 za radne površine sustava Windows slijedi [Fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.


  To se odnosi na sljedeća izdanja: za Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 2012-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2014-12-08T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2013-11-08T00:00:00.000-08:00
  endDate: 2016-01-12T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2013-04-10T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Original Release
  startDate: 2012-11-01T00:00:00.000-08:00
  endDate: 2014-07-08T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pravilnik servisnih paketa](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Izdanja \n* za Windows Desktops"
