### YamlMime:Lifecycle
metadata:
  title: Upravitelj konfiguracije centra sustava Microsoft 2007
  description: Microsoft System Center Configuration Manager 2007 slijedi pravilnik fiksnog životnog ciklusa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 796670fd93547cc79f69c544085070efb0116650
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "808633"
name: Upravitelj konfiguracije centra sustava Microsoft 2007
summary: >
  Microsoft System Center Configuration Manager 2007 slijedi [pravilnik fiksnog](/lifecycle/policies/fixed) životnog ciklusa.



  > [!IMPORTANT]

  > Podrška za ovaj proizvod je završena. Pogledajte smjernice za migraciju u nastavku.
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2007
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Service Pack 2
  startDate: 10/22/2009
  endDate: 07/09/2019
- version: Service Pack 1
  startDate: 05/21/2008
  endDate: 01/11/2011
- version: Original Release
  startDate: 11/29/2007
  endDate: 07/14/2009
content: "\n## <a name=\"links\"></a>Linkovi \n* [Smjernice za migracije](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Informacije o proizvodu](/mem/configmgr/core/understand/introduction)\n* [Pravila servisnog paketa](/lifecycle/policies/fixed#service-packs)"
