### YamlMime:Lifecycle
metadata:
  title: Microsoftova aplikacija za virtualizaciju Hosting 5.0 za radne površine sustava Windows
  description: Microsoftova aplikacija Virtualization Hosting 5.0 za radne površine sustava Windows slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 640b1312c2eba7e693edbd82f34378619036195e
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935367"
name: Microsoftova aplikacija za virtualizaciju Hosting 5.0 za radne površine sustava Windows
summary: >+
  Microsoftova aplikacija Virtualization Hosting 5.0 za radne površine sustava Windows slijedi [Fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.


  To se odnosi na sljedeća izdanja: za radne površine sustava Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 04/14/2026
- version: Service Pack 2
  startDate: 11/08/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pravilnik servisnih paketa](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Izdanja \n* za radne površine sustava Windows"
