### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security slijedi [fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Veze 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security je obustavljen od 14. srpnja 2015. Ažuriranja definicije antimalwarea i antispywarea više neće biti dostupna nakon završetka podrške za verziju proizvoda. Molimo ocijenite System Center Endpoint Protection kao zamjenu.