### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: Microsoft System Center Configuration Manager 2007 slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1b1f1b01df25eb733d93d618831fa157855d5318
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4144110"
name: Microsoft System Center Configuration Manager 2007
summary: >
  Microsoft System Center Configuration Manager 2007 slijedi [fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.



  > [!IMPORTANT]

  > Podrška za ovaj proizvod je završena. Pogledajte smjernice za migraciju u nastavku.
products:
- msc
policyType: fixed
supportDates:
  start: 2007-11-29T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2009-10-22T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2008-05-21T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2007-11-29T00:00:00.000-08:00
  endDate: 2009-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Veze \n* [Smjernice za migracije](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Informacije o proizvodu](/mem/configmgr/core/understand/introduction)\n* [Pravilnik servisnih paketa](/lifecycle/policies/fixed#service-packs)"
