### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 slijedi [fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.


  > [!IMPORTANT]
  > Podrška za ovaj proizvod je završena. Pogledajte smjernice za migraciju u nastavku.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Veze 
  * [Smjernice za migracije](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Dodatne smjernice za migracije](/mem/configmgr/core/migration/planning-for-migration)