### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 za Windows Desktops
  description: Microsoft Application Virtualization Hosting 4.6 za Windows Desktops slijedi Pravilnik fiksnog životnog ciklusa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "808752"
name: Microsoft Application Virtualization Hosting 4.6 za Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 4.6 za Windows Desktops slijedi [Pravilnik fiksnog](/lifecycle/policies/fixed) životnog ciklusa.


  To se odnosi na sljedeća izdanja: za Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Linkovi \n* [Informacije o proizvodu i migraciji](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pravila servisnog paketa](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Budući da klijent App-V 4.6 koristi App-V 4.5 Server, App-V 4.5 Server i dalje će biti podržan prema datumima životnog ciklusa App-V 4.6 kada se koristi s podržanim app-V 4.6 klijentom.\n\n## <a name=\"editions\"></a>Izdanja \n* za Radne površine sustava Windows"
