### YamlMime:Lifecycle
metadata:
  title: Microsoftova aplikacija za virtualizaciju Hosting 5.0 za radne ploče sustava Windows
  description: Microsoftova aplikacija Virtualization Hosting 5.0 za radne površine sustava Windows slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoftova aplikacija za virtualizaciju Hosting 5.0 za radne ploče sustava Windows
summary: |+
  Microsoftova aplikacija Virtualization Hosting 5.0 za radne površine sustava Windows slijedi [Fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.

  To se odnosi na sljedeća izdanja: za Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 04/14/2026
  - version: Service Pack 2
    startDate: 11/08/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>Veze 
  * [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Pravilnik servisnih paketa](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>Izdanja 
  * za Windows Desktops