### YamlMime:Lifecycle
metadata:
  title: Microsoftova aplikacija za virtualizaciju Hosting 5.1 za radne ploče sustava Windows
  description: Microsoft Application Virtualization Hosting 5.1 za Windows Desktops slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: eb73a1103424c9b0900a18fc09bb6bc0685b646d
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4114288"
name: Microsoftova aplikacija za virtualizaciju Hosting 5.1 za radne ploče sustava Windows
summary: >+
  Microsoft Application Virtualization Hosting 5.1 za Windows Desktops slijedi [fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.


  To se odnosi na sljedeća izdanja: za Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 2015-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2015-11-01T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Izdanja \n* za Windows Desktops"
