### YamlMime:Lifecycle
metadata:
  title: Administrator konfiguracije sustava Microsoft System Center (LTSB-verzija 1606)
  description: Administrator konfiguracije sustava Microsoft System Center (LTSB-verzija 1606) slijedi pravilnik o ispravnom životnom ciklusu.
  ms.date: 08/20/2020
  ms.openlocfilehash: 606034d7f3694f3e06a47bdc5e1a45561102c238
  ms.sourcegitcommit: f5095aa6fc41dcc71c883cae08719b5b6bf9585c
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 08/20/2020
  ms.locfileid: "905788"
name: Administrator konfiguracije sustava Microsoft System Center (LTSB-verzija 1606)
summary: >+
  Administrator konfiguracije sustava Microsoft System Center (LTSB-verzija 1606) slijedi pravilnik o [ispravnom](/lifecycle/policies/fixed) životnom ciklusu.


products:
- m365
policyType: fixed
supportDates:
  start: 10/12/2016
  end: 10/12/2021
  extendedEnd: 01/12/2027
releases:
- version: Original Release
  startDate: 10/12/2016
  endDate: 01/12/2027
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o servisiranju i podršci](/sccm/core/understand/learn-more-editions)"
