### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Upravitelj konfiguracije 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 slijedi pravilnik fiksnog životnog ciklusa.
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "850557"
name: Microsoft System Center Upravitelj konfiguracije 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 slijedi [pravilnik fiksnog](/lifecycle/policies/fixed) životnog ciklusa.



  > [!IMPORTANT]

  > Podrška za ovaj proizvod je završena. Pogledajte smjernice za migraciju u nastavku.
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Linkovi \n* [Smjernice za migracije](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Dodatne smjernice za migracije](/mem/configmgr/core/migration/planning-for-migration)"
