### YamlMime:Lifecycle
metadata:
  title: Microsoft Endpoint Configuration Manager
  description: Microsoft Endpoint Configuration Manager slijedi moderni pravilnik o životnom ciklusu.
  ms.date: 02/24/2021
  keywords: SCCM,System Center Configuration Manager
  ms.openlocfilehash: 4821cc920deb11fa6c8c5318a4e383736a447331
  ms.sourcegitcommit: 222ed88a41f7bfe4a9382b99a44b7ce8babc6f51
  ms.translationtype: HT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 03/04/2021
  ms.locfileid: "1453659"
name: Microsoft Endpoint Configuration Manager
summary: >
  Microsoft Endpoint Configuration Manager slijedi [moderni](/lifecycle/policies/modern) pravilnik o životnom ciklusu.



  > [!IMPORTANT]

  > Počevši od verzije 1910, Configuration Manager je sada dio Microsoft Endpoint Manager.
products:
- m365
policyType: modern-on-prem
supportDates:
  start: 12/08/2015
releases:
- version: Version 2010
  startDate: 11/30/2020
  endDate: 05/30/2022
- version: Version 2006
  startDate: 08/11/2020
  endDate: 02/11/2022
- version: Version 2002
  startDate: 04/01/2020
  endDate: 10/01/2021
- version: Version 1910
  startDate: 11/29/2019
  endDate: 05/29/2021
- version: Version 1906
  startDate: 07/26/2019
  endDate: 01/26/2021
- version: Version 1902
  startDate: 03/27/2019
  endDate: 09/27/2020
- version: Version 1810
  startDate: 11/27/2018
  endDate: 12/01/2020
- version: Version 1806
  startDate: 07/31/2018
  endDate: 01/31/2020
- version: Version 1802
  startDate: 03/22/2018
  endDate: 09/22/2019
- version: Version 1710
  startDate: 11/20/2017
  endDate: 05/20/2019
- version: Version 1706
  startDate: 07/31/2017
  endDate: 07/31/2018
- version: Version 1702
  startDate: 03/27/2017
  endDate: 03/27/2018
- version: Version 1610
  startDate: 11/18/2016
  endDate: 11/18/2017
- version: Version 1606 with KB3186654
  startDate: 10/12/2016
  endDate: 10/12/2017
- version: Version 1606
  startDate: 07/22/2016
  endDate: 07/22/2017
- version: Version 1602
  startDate: 03/11/2016
  endDate: 03/11/2016
- version: Version 1511
  startDate: 12/08/2015
  endDate: 12/08/2016
content: "\n## <a name=\"links\"></a>Veze \n* [Informacije o servisiranju](/mem/configmgr/core/servers/manage/current-branch-versions-supported)\n* [Pojedinosti o verziji](/mem/configmgr/core/servers/manage/updates#version-details)\n* [Upravitelj konfiguracije sistemskog centra je sada Microsoft Endpoint Configuration Manager](/mem/configmgr/core/understand/microsoft-endpoint-manager-faq)\n* [Povijesne verzije](/mem/configmgr/core/servers/manage/updates#historical-versions)\n* [Što je Upravitelj konfiguracije](/mem/configmgr/core/understand/introduction)"
