### YamlMime:Lifecycle
metadata:
  title: Sigurnost klijentskog sustava Microsoft Forefront
  description: Klijentska sigurnost sustava Microsoft Forefront slijedi pravilo o ispravnom životnom ciklusu.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908660"
name: Sigurnost klijentskog sustava Microsoft Forefront
summary: >+
  Klijentska sigurnost sustava Microsoft Forefront slijedi pravilo o [ispravnom](/lifecycle/policies/fixed) životnom ciklusu.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Veze \n* [Zaštita krajnje točke u centru sustava](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Sigurnost klijenta u programu Forefront ukinuta je. Podrška završava 14. srpnja, 2015. Ažuriranja definicija antizlonamjernog softvera i antispyware više neće biti dostupna nakon završetka podrške za verziju proizvoda. Odaberite zaštitu krajnje točke sustava Center kao zamjenu."
