### YamlMime:Lifecycle
metadata:
  title: Virtualizacija Microsoftove aplikacije 5.1
  description: Microsoft Application Virtualization 5.1 slijedi pravilnik fiksnog životnog ciklusa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 3f0cac2ee013dd73e44fe41d9ba1d07cfcfce2f1
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "850274"
name: Virtualizacija Microsoftove aplikacije 5.1
summary: >+
  Microsoft Application Virtualization 5.1 slijedi [pravilnik fiksnog](/lifecycle/policies/fixed) životnog ciklusa.


  To se odnosi na sljedeća izdanja: za servise udaljene radne površine za Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Linkovi \n* [Informacije o proizvodu](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Izdanja \n* za servise udaljene radne površine\n* za Radne površine sustava Windows"
