### YamlMime:Lifecycle
metadata:
  title: PixelSense Applications Suite 1.0
  description: PixelSense Applications Suite 1.0 slijedi fiksni pravilnik životnog ciklusa.
  ms.date: 08/12/2020
  ms.openlocfilehash: 3f929410194b40d875c8bb3618144739536874e1
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: hr-HR
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4143629"
name: PixelSense Applications Suite 1.0
summary: >+
  PixelSense Applications Suite 1.0 slijedi [fiksni](/lifecycle/policies/fixed) pravilnik životnog ciklusa.


products:
- windows
policyType: fixed
supportDates:
  start: 2009-01-01T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 1
  startDate: 2009-08-09T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2009-01-01T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
content: ''
